spring:
  application:
    name: discovery
server:
  port: 8082

eureka:

  instance:
    hostname: localhost
    statusPageUrlPath: ${management.server.servlet.context-path}/info
    healthCheckUrlPath: ${management.server.servlet.context-path}/health

  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
    register-with-eureka: false
    register-with-eureka: false
    healthcheck:
      enabled: true

