spring:
  application:
    name: discovery
server:
  port: ${DISCOVERY_SERVER_PORT:8761}

eureka:

  instance:
    hostname: localhost
    statusPageUrlPath: ${management.server.servlet.context-path}/info
    healthCheckUrlPath: ${management.server.servlet.context-path}/health

  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF