spring:
  application:
    name: discovery


server:
  port: ${DISCOVERY_SERVER_PORT:8082}
  servlet-path: /${spring.application.name}

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/discovery/
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true