spring:
  application:
    name: discovery
server:
  port: 8082

eureka:

  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
    register-with-eureka: false
    register-with-eureka: false

